CREATE DATABASE ZORVYN;

CREATE TABLE users (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL, -- WILL STORE'ROLE_VIEWER', 'ROLE_ANALYST', 'ROLE_ADMIN'
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE financial_records (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(15,2) NOT NULL,
    type VARCHAR(50) NOT NULL, -- WILL STORE 'INCOME' OR 'EXPENSE'
    category VARCHAR(100) NOT NULL,
    record_data DATE NOT NULL,
    notes TEXT,
    created_by BIGINT, -- Links to users.id to track who added the record
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (created_by) REFERENCES users(id)
);